In [58]:
import matplotlib.pyplot as plt
import matplotlib as mpl
import numpy as np
from PIL import Image
Image.MAX_IMAGE_PIXELS = None

im = Image.open("../../Raw_Data_21_zones/DEM05m_ClipGrid.tif")
box = (2625*3, 1 + 3000 * 2, 2625*4, 1 + 3000 * 3)
croppedImage = im.crop(box)


croppedImage.save("../cropped_data/test.tif")


In [59]:
plt.figure(num=None, figsize=(30,30), facecolor='w', edgecolor='k')
plt.rcParams.update({'font.size':22})
ax = [plt.subplot(1,1,i+1) for i in range(1)]
for a in ax:
    a.set_xticklabels([])
    a.set_yticklabels([])
    a.tick_params(bottom=False, left=False)
plt.subplots_adjust(wspace=0,hspace=0.04)

imArr = np.asarray(Image.open("../cropped_data/test.tif"))

ax[0].title.set_text("test")
ax[0].imshow(imArr)

In [60]:
#imArr = np.asarray(Image.open("../../Raw_Data_21_zones/Slope_ClipGrid.tif"))

In [61]:
imArr.shape

(3000, 2625)

In [62]:
for i in range(len(imArr)):
    print(imArr[i])

[1132470519 1132468475 1132467430 ... 1134100739 1134106236 1134106434]
[1132470485 1132469590 1132467930 ... 1134104971 1134110720 1134110996]
[1132470719 1132470240 1132468434 ... 1134106372 1134110849 1134115796]
[1132470549 1132470332 1132468519 ... 1134107731 1134110354 1134117989]
[1132470150 1132470611 1132469376 ... 1134108206 1134109783 1134119608]
[1132471485 1132471037 1132470424 ... 1134110981 1134112099 1134122554]
[1132472294 1132471361 1132469631 ... 1134113672 1134114595 1134123125]
[1132472208 1132471049 1132468676 ... 1134116257 1134117106 1134123362]
[1132470233 1132470373 1132468014 ... 1134120749 1134121015 1134124821]
[1132471456 1132471467 1132468529 ... 1134124541 1134124354 1134126176]
[1132472830 1132472959 1132471209 ... 1134126913 1134127004 1134126843]
[1132474041 1132473549 1132471663 ... 1134127359 1134128929 1134130305]
[1132475201 1132474398 1132468122 ... 1134127507 1134131116 1134132533]
[1132472897 1132473070 1132467982 ... 1134130129 1134134064 1134