In [6]:
import numpy as np
import math

In [142]:
def foo(arr, grid_size=(5,5)):
    width,height = grid_size
    holder_size = (len(arr)//width*height)+1
    holder = np.zeros([holder_size, width*height])
    for i in range(0, len(arr), width):
        ix = i+width
        for j in range(0, len(arr[0]), height):
            jy = j+height
            print(arr[:ix,:jy])
            
    return holder

In [143]:
foo(np.asarray([[0,1,0,1,0],
     [1,0,1,0,1],
     [0,1,0,0,0],
     [1,0,0,0,0]]),
    (2,2))

[[0 1]
 [1 0]]
[[0 1 0 1]
 [1 0 1 0]]
[[0 1 0 1 0]
 [1 0 1 0 1]]
[[0 1]
 [1 0]
 [0 1]
 [1 0]]
[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 0]
 [1 0 0 0]]
[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 0 0]
 [1 0 0 0 0]]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

4